spring:
  profiles:
  active:
    - dev
---
spring:
  profiles: dev
  application:
  name: cloud-config-atguigu-dev
---
spring:
  profiles: test #测试环境application:
  name: cloud-config-atguigu-test
  #请保存为UTF-8格式
